#!/usr/bin/env node
// Renders tools/oracle/results/latest.json into tools/oracle/REPORT.generated.md.
// Raw results and verdicts stay separate; this only joins them for reading.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const here = path.dirname(new URL(import.meta.url).pathname);
const data = JSON.parse(readFileSync(path.join(here, "results/latest.json"), "utf8"));
const isMutant = (r) => r.impl.startsWith("MUTANT");
const recs = data.records.filter((r) => r.group !== "controls" && r.group !== "real" && !isMutant(r));
const intRecs = data.records.filter((r) => r.group === "controls" || r.group === "real");
const controls = data.records.filter((r) => r.expect);

function confidence(rs) {
  const real = rs.find((r) => r.domain === "realistic") ?? rs.find((r) => r.kind !== "pure");
  const tags = [];
  if (!real) return "BASIC";
  tags.push("BASIC");
  if (real.result === "MATCH_OBSERVED") {
    if (real.cases.boundary > 0) tags.push("BOUNDARY_TESTED");
    if (real.cases.fuzz > 0) tags.push("FUZZ_TESTED");
    if (real.kind === "rng" || real.kind === "buffer") tags.push("STATE_VERIFIED");
  }
  return tags.join(" + ");
}

const lines = [];
lines.push("# Differential oracle: generated report", "");
lines.push("Generated by `node tools/oracle/report.mjs` from `results/latest.json` + `verdicts.json`. Do not edit by hand.", "");
lines.push("**What this is.** pokefirered C compiled with clang/wasm32 (semantic reference for pure C logic) compared with the real `src/fr` TypeScript.",
  "It is NOT a GBA emulator and NOT an exact reproduction of agbcc or the ARM ABI. `MATCH_OBSERVED` means only: no difference in the inputs tried and the effects observed. It is not a proof of equivalence.", "");
lines.push(`Toolchain: ${data.metrics.toolchain.clang}; ${data.metrics.toolchain.wasmLd}`);
lines.push(`Compile flags: \`${data.metrics.cflags.join(" ")} ${data.metrics.ldflags.join(" ")}\``);
lines.push(`Seed: ${data.seed}, fuzz cases per domain: ${data.fuzz}, boundary-combination cap: ${data.cap}`, "");

// ---- per function
lines.push("## Results by function", "");
lines.push("| Function | TS implementation | Domain | Boundary | Fuzz | Raw result | Verdicts | Observed |", "|---|---|---|---:|---:|---|---|---|");
for (const r of recs) {
  const vs = Object.entries(r.clusters).map(([c, info]) => `${c}: ${r.verdicts[c]?.verdict ?? "UNRESOLVED"} (${info.count})`);
  lines.push(`| ${r.fn} | ${r.impl} | ${r.domain} | ${r.cases.boundary} | ${r.cases.fuzz} | ${r.result} | ${vs.join("; ") || "-"} | ${r.observed} |`);
}
lines.push("");

// ---- verdict tally
const tally = {};
let unresolved = 0;
for (const r of recs) for (const c of Object.keys(r.clusters)) {
  const v = r.verdicts[c]?.verdict;
  if (v) tally[v] = (tally[v] ?? 0) + 1; else unresolved++;
}
lines.push("## Divergence clusters by verdict", "");
lines.push("Clusters, not cases: one cluster groups all mismatches with the same automatic cause hint for one function/impl/domain.", "");
lines.push("| Verdict | Clusters |", "|---|---:|");
for (const k of ["TS_DIVERGENCE", "DATA_MISMATCH", "UNDEFINED_BEHAVIOR", "INVALID_DOMAIN", "ORACLE_LIMITATION", "HARNESS_ERROR"]) lines.push(`| ${k} | ${tally[k] ?? 0} |`);
lines.push(`| (unresolved: NEEDS_TRIAGE) | ${unresolved} |`, "");

// ---- confidence
lines.push("## Confidence per function (qualitative)", "");
lines.push("Only the realistic domain counts towards confidence. Type-domain mismatches are listed above with their verdict.", "");
lines.push("| Function | TS implementation | Confidence | Realistic-domain result | Adapters used | Limitations |", "|---|---|---|---|---|---|");
const keys = [...new Set(recs.filter((r) => !r.impl.startsWith("data:") && !r.impl.startsWith("layout:")).map((r) => `${r.fn}|${r.impl}`))];
for (const k of keys) {
  const [fn, impl] = k.split("|");
  const rs = recs.filter((r) => r.fn === fn && r.impl === impl);
  const real = rs.find((r) => r.domain === "realistic") ?? rs[0];
  const data = recs.some((r) => r.fn === fn && r.impl.startsWith("data:") && r.result === "MATCH_OBSERVED") ? " + DATA_CHECKED" : "";
  const lim = real.realistic?.some((e) => e.level === "assumed") ? "realistic domain partly ASSUMED" : "realistic domain from callers";
  lines.push(`| ${fn} | ${impl} | ${confidence(rs)}${data} | ${real.result} | ${(real.adapters ?? []).join(", ") || "none"} | ${lim} |`);
}
lines.push("");

// ---- INT: C/wasm vs generator before INT vs generator with INT
if (intRecs.length) {
  lines.push("## INT: generator before vs after, against C/wasm", "");
  lines.push("Cells are `result (mismatching cases)`. `-` means that generator rejected the function. Remaining INT mismatches in the type domain are undefined behaviour (trap, out-of-table index) unless a verdict says otherwise.", "");
  lines.push("| Group | Function | Domain | before INT | with INT | hand-fixed |", "|---|---|---|---|---|---|");
  const cell = (x) => (x ? `${x.result === "MATCH_OBSERVED" ? "MATCH" : "NEEDS_TRIAGE"} (${x.mismatches})` : "-");
  const keys2 = [...new Set(intRecs.map((r) => `${r.group}|${r.fn}|${r.domain}`))];
  for (const k of keys2) {
    const [g, fn, dom] = k.split("|");
    const at = (label) => intRecs.find((r) => r.group === g && r.fn === fn && r.domain === dom && r.impl === label);
    lines.push(`| ${g} | ${fn} | ${dom} | ${cell(at("generated (before INT)"))} | ${cell(at("generated (INT)"))} | ${cell(at("fixed"))} |`);
  }
  lines.push("");
}

// ---- detector validity
const bad = controls.filter((r) => r.expect !== r.result);
lines.push("## Detector validity (positive controls)", "");
lines.push(`${controls.length - bad.length}/${controls.length} control runs behaved as expected. The 'generated' TS is emitted by the current \`tools/decomp/clang_codegen.py\` and is known to be wrong for u8 overflow, s8 casts, u32 mul/shr and static locals; the 'fixed' TS is hand-written.`, "");
lines.push("| Control | TS | Expected | Observed |", "|---|---|---|---|");
for (const r of controls) lines.push(`| ${r.fn} | ${r.impl} | ${r.expect} | ${r.result} |`);
lines.push("");

// ---- C-side cost
lines.push("## C side: cost of compiling a whole translation unit", "");
lines.push("Each function is compiled as its full preprocessed `.c`. Imports are functions the unit calls that are defined elsewhere (stubbed to throw if reached); undefined symbols include data the unit references but does not define.", "");
lines.push("| Unit | wasm bytes | imports (libc-provided / stubbed) | undefined symbols | compile ms |", "|---|---:|---|---:|---:|");
for (const [k, m] of Object.entries(data.metrics.c)) lines.push(`| ${path.basename(k)} | ${m.wasmBytes} | ${m.imports} (${m.libcProvided.length} / ${m.stubbed}) | ${m.undefinedSymbols} | ${m.compileMs} |`);
lines.push("", `TS bundle: ${data.metrics.ts.modules} modules, ${data.metrics.ts.bundleMs} ms. Run: ${data.metrics.runMs} ms.`, "");
writeFileSync(path.join(here, "REPORT.generated.md"), lines.join("\n") + "\n");
console.log("wrote tools/oracle/REPORT.generated.md");
