"""TypeScript for a small set of REAL pokefirered functions, from the generator BEFORE the INT work (frozen baseline)
and from the CURRENT one. Only functions a generator can accept without structs/pointers are listed.

Usage: python3 tools/oracle/controls/gen_real.py <out_prefix>
Writes <out_prefix>_old.ts and <out_prefix>_new.ts. Read-only use of both generators; tables the functions read
(`const` arrays in the C unit) are supplied from the exported cdata so the generated module is runnable.
"""
import importlib.util
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "tools" / "decomp"))
import clang_ast  # noqa: E402
import clang_codegen  # noqa: E402
import clang_intsem  # noqa: E402
from common import DECOMP  # noqa: E402

BASELINE = ROOT / "tools" / "oracle" / "baseline" / "clang_codegen_before_int.py"
spec = importlib.util.spec_from_file_location("clang_codegen_before_int", BASELINE)
old = importlib.util.module_from_spec(spec)
spec.loader.exec_module(old)

MANIFEST = [
    ("util", "CountTrailingZeroBits"), ("util", "CalcCRC16"),
    ("battle_anim", "CalculatePanIncrement"), ("battle_anim", "KeepPanInRange"),
    ("pokemon", "IsShinyOtIdPersonality"), ("pokemon", "ModifyStatByNature"),
    ("bg", "GetTileMapIndexFromCoords"),
    ("battle_interface", "GetScaledHPFraction"), ("battle_interface", "GetHPBarLevel"), ("battle_interface", "GetReceivedValueInPixels"),
    ("sprite", "GetAnchorCoord"), ("itemfinder", "GetPlayerDirectionTowardsHiddenItem"),
    ("trig", "Sin"), ("trig", "Cos"), ("random", "Random"), ("fieldmap", "ExtractMetatileAttribute"),
]

emitters = {"old": [], "new": []}
tables: dict[str, object] = {}
stems = sorted({s for s, _ in MANIFEST})
for stem in stems:
    ast = clang_ast.dump_clang_ast_json(DECOMP / "src" / f"{stem}.c")
    names = {n for s, n in MANIFEST if s == stem}
    funcs = clang_ast.extract_functions(ast, names)
    enums = clang_intsem.enum_constants(ast)
    cdata = ROOT / "public" / "fr" / "cdata" / f"{stem}.json"
    defs = json.loads(cdata.read_text())["defs"] if cdata.exists() else {}
    for _, name in [m for m in MANIFEST if m[0] == stem]:
        f = funcs[name]
        for label, mk in (("old", lambda: old.ClangTsEmitter(f"{stem}.c", f)),
                          ("new", lambda: clang_codegen.ClangTsEmitter(f"{stem}.c", f, named_constants=False, enums=enums))):
            try:
                code = mk().emit_function()
            except Exception as exc:  # rejected by that generator: no TS, not compared
                code = f"// {name}: rejected: {getattr(exc, 'reason', exc)}"
            emitters[label].append((code, defs))

for label, items in emitters.items():
    body = "\n\n".join(c for c, _ in items)
    pre = ['import { readFileSync } from "node:fs";']
    if re.search(r"\babs\(", body):
        pre.append("const abs = Math.abs;")
    if re.search(r"\bgRngValue\b", body):
        pre.append("let gRngValue = 0;")
    seen = set()
    for _, defs in items:
        for k, v in defs.items():
            if k not in seen and re.search(rf"\b{re.escape(k)}\b", body) and isinstance(v.get("value"), list):
                seen.add(k)
                pre.append(f"const {k} = {json.dumps(v['value'])};")
    Path(f"{sys.argv[1]}_{label}.ts").write_text("// Generated by tools/oracle/controls/gen_real.py\n" + "\n".join(pre) + "\n\n" + body + "\n")
