"""Emit TypeScript for controls.c with the generator BEFORE the INT work (frozen baseline) and the CURRENT one.

Usage: python3 tools/oracle/controls/gen_controls.py <out_prefix>
Writes <out_prefix>_old.ts (tools/oracle/baseline/clang_codegen_before_int.py) and <out_prefix>_new.ts
(tools/decomp/clang_codegen.py). Both are read-only uses of the generators.
"""
import importlib.util
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "tools" / "decomp"))
import clang_ast  # noqa: E402
import clang_codegen  # noqa: E402
import clang_intsem  # noqa: E402

BASELINE = ROOT / "tools" / "oracle" / "baseline" / "clang_codegen_before_int.py"
spec = importlib.util.spec_from_file_location("clang_codegen_before_int", BASELINE)
old = importlib.util.module_from_spec(spec)
spec.loader.exec_module(old)

src = Path(__file__).with_name("controls.c")
res = subprocess.run(
    ["clang", "--target=armv4t-none-eabi", "-funsigned-char", "-Xclang", "-ast-dump=json", "-fsyntax-only", "-w", str(src)],
    capture_output=True, check=True,
)
ast = json.loads(res.stdout)
funcs = clang_ast.extract_functions(ast)
enums = clang_intsem.enum_constants(ast)

for label, emit in (("old", lambda f: old.ClangTsEmitter("controls.c", f).emit_function()),
                    ("new", lambda f: clang_codegen.ClangTsEmitter("controls.c", f, named_constants=False, enums=enums).emit_function())):
    out = [f"// Generated by tools/oracle/controls/gen_controls.py ({label} generator)."]
    for name, f in funcs.items():
        try:
            out.append(emit(f))
        except Exception as exc:  # a rejected function simply has no TS in that variant
            out.append(f"// {name}: rejected: {getattr(exc, 'reason', exc)}")
    Path(f"{sys.argv[1]}_{label}.ts").write_text("\n".join(out) + "\n")
