#!/usr/bin/env python3
"""Extract viewer track transitions/lifetime from FR; --check rejects stale output."""
from pathlib import Path
import argparse
import re
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "decomp"))
from common import DECOMP, ROOT
from step_objects import strip_comments


def extract(movement: str, helpers: str) -> str:
    table = re.search(r"static const u8 bikeTireTracks_Transitions\[(\d+)\]\[(\d+)\]\s*=\s*\{([^}]+)\}", strip_comments(movement))
    if not table or table.group(1, 2) != ("4", "4"):
        raise ValueError("event_object_movement.c: unsupported track table shape")
    body = table.group(3)
    if not re.fullmatch(r"[\s\d,]+", body):
        raise ValueError("event_object_movement.c: unsupported track table expression")
    entries = [int(v) for v in re.findall(r"\d+", body)]
    if len(entries) != 16 or any(v < 1 or v > 8 for v in entries):
        raise ValueError("event_object_movement.c: invalid transition entries")
    index = re.search(r"bikeTireTracks_Transitions\[objEvent->previousMovementDirection\]\[objEvent->facingDirection - (\d+)\]", movement)
    if not index:
        raise ValueError("event_object_movement.c: unsupported transition addressing")
    clean = strip_comments(helpers)
    wait = re.search(r"static void FadeFootprintsTireTracks_Step0\([^)]*\)\s*\{\s*if \(\+\+sprite->data\[1\] > (\d+)\)\s*sprite->data\[0\] = 1;", clean)
    end = re.search(r"static void FadeFootprintsTireTracks_Step1\([^)]*\)\s*\{\s*sprite->invisible \^= 1;\s*sprite->data\[1\]\+\+;\s*UpdateObjectEventSpriteInvisibility\(sprite, sprite->invisible\);\s*if \(sprite->data\[1\] > (\d+)\)", clean)
    if not wait or not end or int(wait.group(1)) >= int(end.group(1)):
        raise ValueError("field_effect_helpers.c: unsupported lifetime state machine")
    return ("// Generated by python3 tools/viewer/track_effects.py; do not edit.\n"
            "// Sources: event_object_movement.c DoTracksGroundEffect_BikeTireTracks;\n"
            "// field_effect_helpers.c FadeFootprintsTireTracks_Step0/Step1.\n"
            f"export const BIKE_TRACK_TRANSITIONS = {entries} as const;\n"
            f"export const TRACK_ROW_WIDTH = {table.group(2)};\n"
            f"export const TRACK_INDEX_OFFSET = {index.group(1)};\n"
            f"export const TRACK_HOLD_TICKS = {int(wait.group(1)) + 1};\n"
            f"export const TRACK_END_TICK = {int(end.group(1)) + 1};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    movement = (DECOMP / "src/event_object_movement.c").read_text()
    helpers = (DECOMP / "src/field_effect_helpers.c").read_text()
    output = extract(movement, helpers)
    # Unsupported changes must fail, never silently emit an approximation.
    for broken in [movement.replace("Transitions[4][4]", "Transitions[5][4]"), movement.replace("1, 2, 7, 8", "1, 2, UNKNOWN, 8")]:
        try:
            extract(broken, helpers)
        except ValueError:
            pass
        else:
            raise AssertionError("Unsupported source accepted")
    assert extract(movement, helpers) == output
    target = ROOT / "src/viewer/generated/trackEffects.ts"
    if args.check:
        assert target.read_text() == output, "Stale viewer track data: regenerate"
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(output)
    print("Viewer track transitions/lifetime match C")


if __name__ == "__main__":
    main()
