"""Generate src/fr/generated/constants.ts: every integer #define and enum
member of the decompilation's headers, evaluated by the host compiler.
"""

from __future__ import annotations

import re
import subprocess

from common import BUILD, CPP_DEFINES, DECOMP, GEN_INCLUDE, GENERATED, ROOT

SKIP_HEADERS = {"gba/m4a_internal.h", "gba/isagbprint.h", "gba/multiboot.h", "gba/flash_internal.h", "gba/syscall.h", "global.fieldmap.h", "global.berry.h", "global.tv.h", "constants/global.h"}


def header_list() -> list[str]:
    headers = []
    for base in (DECOMP / "include", GEN_INCLUDE):
        for path in sorted(base.rglob("*.h")):
            rel = path.relative_to(base).as_posix()
            if rel in SKIP_HEADERS or rel.startswith(("gba/", "data/")):
                continue
            headers.append(rel)
    # global.h first
    return ["global.h"] + [h for h in dict.fromkeys(headers) if h != "global.h"]


def compiles(headers: list[str]) -> bool:
    probe = BUILD / "tsconst_try.c"
    probe.write_text("".join(f'#include "{h}"\n' for h in headers) + "int main(void){return 0;}\n")
    r = subprocess.run(["clang", "-fsyntax-only", "-w", "-x", "c", *CPP_DEFINES, "-I", str(BUILD), "-I", str(GEN_INCLUDE), "-iquote", "include", "-I", "include", str(probe)], cwd=DECOMP, capture_output=True)
    return r.returncode == 0


def usable_headers() -> list[str]:
    headers = header_list()
    ok = ["global.h"]
    for h in headers[1:]:
        if compiles(ok + [h]):
            ok.append(h)
    return ok


IDENT = re.compile(r"\b([A-Za-z_]\w*)\b")


def export_ts_constants() -> None:
    headers = usable_headers()
    include = BUILD / "tsconst_probe.h"
    include.write_text("".join(f'#include "{h}"\n' for h in headers))
    macros = subprocess.run(["clang", "-E", "-dM", "-x", "c", *CPP_DEFINES, "-I", str(BUILD), "-I", str(GEN_INCLUDE), "-iquote", "include", "-I", "include", str(include)], cwd=DECOMP, capture_output=True).stdout.decode()
    names: list[str] = []
    for line in macros.splitlines():
        m = re.match(r"#define ([A-Z][A-Z0-9_]*) (.+)$", line)
        if not m:
            continue
        name, value = m.groups()
        if name.startswith("__") or value.strip().startswith('"'):
            continue
        if "*" in value and re.search(r"\(\s*\*", value):
            continue  # dereferences (REG_*, pointers)
        if any(re.match(r"[gs][A-Z]", ident) for ident in IDENT.findall(value)):
            continue  # depends on variables
        if re.search(r"\b(sizeof|offsetof)\b", value) and "struct" not in value and not re.search(r"sizeof\s*\(\s*[A-Z]", value):
            pass
        names.append(name)
    # enum members
    pre = subprocess.run(["clang", "-E", "-P", "-x", "c", *CPP_DEFINES, "-I", str(BUILD), "-I", str(GEN_INCLUDE), "-iquote", "include", "-I", "include", str(include)], cwd=DECOMP, capture_output=True).stdout.decode()
    for block in re.findall(r"enum\s*\w*\s*\{([^}]*)\}", pre):
        for member in re.findall(r"(?:^|,)\s*([A-Z][A-Z0-9_a-z]*)\s*(?==|,|$)", block.strip(), flags=re.S):
            names.append(member)
    names = sorted(set(names))
    rejected: set[str] = set()
    exe = BUILD / "tsconst_probe"
    for _ in range(40):
        keep = [n for n in names if n not in rejected]
        body = "\n".join(f'printf("%s %lld\\n", "{n}", (long long)({n}));' for n in keep)
        src = BUILD / "tsconst_probe.c"
        src.write_text(f'#include "tsconst_probe.h"\n#include <stdio.h>\nint main(void){{\n{body}\nreturn 0;}}\n')
        r = subprocess.run(["clang", "-w", "-x", "c", *CPP_DEFINES, "-I", str(BUILD), "-I", str(GEN_INCLUDE), "-iquote", "include", "-I", "include", str(src), "-o", str(exe)], cwd=DECOMP, capture_output=True)
        if r.returncode == 0:
            break
        err = r.stderr.decode()
        bad = {int(x) for x in re.findall(r"tsconst_probe\.c:(\d+):\d+: error", err)}
        undefined = set(re.findall(r'"_([A-Za-z_]\w*)", referenced from', err))
        if not bad and not undefined:
            raise RuntimeError(err[:3000])
        for line in bad:
            idx = line - 4
            if 0 <= idx < len(keep):
                rejected.add(keep[idx])
        if undefined:
            # linker errors: drop names whose macro text mentions the symbol
            for n in keep:
                mm = re.search(rf"#define {n} (.+)$", macros, flags=re.M)
                if mm and any(u in mm.group(1) for u in undefined):
                    rejected.add(n)
    out = subprocess.run([str(exe)], capture_output=True).stdout.decode()
    values: dict[str, int] = {}
    for line in out.splitlines():
        name, value = line.rsplit(" ", 1)
        values[name] = int(value)
    ts = ["// Generated by tools/decomp/step_tsconst.py from the decompilation headers. Do not edit.", "/* eslint-disable */"]
    for name in sorted(values):
        v = values[name]
        ts.append(f"export const {name} = {v};")
    target = GENERATED / "constants.ts"
    GENERATED.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(ts) + "\n")
    print(f"  ts constants: {len(values)} from {len(headers)} headers ({len(rejected)} rejected)")
