// REAL pokefirered functions generated by tools/decomp (before INT vs INT) and compared with C/wasm.
// Each spec reuses the parameter types and domains (with their evidence) of the hand-port spec of the same function;
// only the implementations differ. No expectations are asserted: the point is the three-way table.
import a from "./groupA.mjs";
import b from "./groupB.mjs";
import c from "./groupC.mjs";

const P = (n, t, extra = {}) => ({ n, t, ...extra });
const all = [...a, ...b, ...c];
const impls = (name) => [
  { label: "generated (before INT)", mjs: "real_generated_old", name },
  { label: "generated (INT)", mjs: "real_generated_new", name },
];
const reuse = (name, over = {}) => {
  const base = all.find((s) => s.name === name);
  const { setup, dataChecks, tsExtra, extraExpose, cost, impls: _i, ...rest } = base;
  return { ...rest, group: "real", impls: impls(name), cost: { specLines: 1, wrapper: "none", state: "none", touchedTs: false, adapters: [], reusable: "n/a" }, ...over };
};

export default [
  reuse("CountTrailingZeroBits"), reuse("CalcCRC16"), reuse("CalculatePanIncrement"), reuse("IsShinyOtIdPersonality"),
  reuse("ModifyStatByNature"), reuse("GetTileMapIndexFromCoords"), reuse("GetScaledHPFraction"), reuse("GetHPBarLevel"),
  // regression: the generator reproduces the manual fix, so hand port, generated (INT) and C/wasm must all agree
  reuse("GetReceivedValueInPixels", { impls: [...impls("GetReceivedValueInPixels"), { label: "hand port (battle/interface.ts)", file: "src/fr/battle/interface.ts", name: "GetReceivedValueInPixels" }] }),
  reuse("GetAnchorCoord"), reuse("GetPlayerDirectionTowardsHiddenItem"),
  reuse("Sin"), reuse("ExtractMetatileAttribute"),
  { ...reuse("Sin"), name: "Cos", c: { stem: "trig", name: "Cos" }, impls: impls("Cos") },
  {
    name: "KeepPanInRange", group: "real", kind: "pure", ret: "s16", c: { stem: "battle_anim", name: "KeepPanInRange" },
    params: [P("panArg", "s16", { realistic: [-64, 63] }), P("oldPan", "s32", { realistic: [-64, 63] })], impls: impls("KeepPanInRange"),
    realisticEvidence: [{ level: "fact", text: "pans are SOUND_PAN_ATTACKER..SOUND_PAN_TARGET (-64..63)", refs: ["constants/battle_anim.h:317"] }],
    cost: { specLines: 1, wrapper: "none", state: "none", touchedTs: false, adapters: [], reusable: "n/a" },
  },
  {
    name: "Random", group: "real", kind: "pure", ret: "u16", c: { stem: "random", name: "Random" }, params: [], impls: impls("Random"),
    observed: "2001 consecutive calls from gRngValue = 0 (state persists on both sides)",
    cost: { specLines: 1, wrapper: "none", state: "module-level gRngValue in the generated file", touchedTs: false, adapters: [], reusable: "n/a" },
  },
].map((s) => (s.name === "GetScaledHPFraction" ? { ...s, pairCompare: false, extraDomains: undefined } : s));
